### ISSUE TITLE
Connection error in NEURON

### ISSUE THREAD

**Issue by lmanubens** [MarcelBeining/T2N#3]
I'm trying to simulate from a single swc. 
In order to do so I'm basically using the t2n_Tutorial.m code just defining the variable "tree" from a local swc file. I attached a snapshot of the error I got and the swc file being used.

I just changed line 70 in t2n_Tutorial.m:
`tree = {sample_tree};   % load sample tree`

To:
```
start_trees
load_tree('morphos/test.swc')
tree = trees;   % load tree
for r=1:length(tree{1}.D)
    if(tree{1}.D(r)>3) 
        tree{1}.R(r) = 1;   % set region in nodes surrounding the soma "soma"
    end
end

tree{1}.rnames{1} = 'soma';   % name the region "soma"
tree{1}.rnames{2} = 'dendrite';   % name the region "dendrite"
tree{1}.rnames{3} = 'dendrite';   % name the region "dendrite"
for r=4:length(tree{1}.rnames)
    tree{1}.rnames{r} = 'axon';   % name the region "axon"
end

tree{1}.Ri=100;
tree{1}.Gm=5e-4;
tree{1}.Cm=1;
tree{1}.name='cell_test';
```
And added HH Sodium channel to axon after Line 61:
`    neuron.mech{t}.axon.hh = struct('gnabar',0.25,'gkbar',0.036,'gl',0);     % add Hodgkin-Huxley Sodium channel only to axon`

I have also tried reapiring and sorting the tree, but it seems to be BCT conform already.

Thanks in advance!

[t2n_connect.zip](https://github.com/MarcelBeining/T2N/files/2606451/t2n_connect.zip)

**Comment by MarcelBeining** [comment]
Hi Linus,
thanks for the report.
Unfortunately, the error message is so long, such that it does not show you all of the errors in the error message dialog. Nevertheless, it already gives you a hint:
It seems that something is wrong with your morphology. I did some checks and graphisdag(tree{1}.dA) returns 1 meaning you have one or several loops/cycles in your morphology! However, loops in directed trees are forbidden! You have to find and fix these loops in order to work with that morphology in T2N and trees.
I will add a check in treestoolbox load_tree to give a warning when loops are detected.

PS: You can simplify the following lines
```
start_trees
load_tree('morphos/test.swc')
tree = trees;   % load tree
```
with this:
`tree = {load_tree('morphos/test.swc')}`
Generally I do not recommend using the global variable trees to avoid some function changing a tree of you and you do not notice.

**Comment by lmanubens** [comment]
Hi Marcel,

Thank you very much, this was a bit embarrassing.
I have made sure no loops are there in other swc files and the tutorial code runs quite smoothly :D
I still have an issue though, I will open a new thread to keep the issues organized.

Thanks a lot for your help!
Linus
