### ISSUE TITLE
undefined function geom_nseg and mpiexec problems on Mac

### ISSUE THREAD

**Issue by LauraDovek** [MarcelBeining/T2N#9]
![image](https://user-images.githubusercontent.com/52047233/60471377-3d6a4180-9c19-11e9-9c4f-7a7725686c12.png)

Hello, Any idea why I might be getting this error? I am trying to walk through the t2n_tutorial_live.mlx. to learn how to use it but I keep running into various problems. 
Kind Regards, 
Laura

**Comment by MarcelBeining** [comment]
Hi @LauraDovek ,
sounds like NEURON does not find the geom_nseg procedure which is defined in lib_genroutines/genroutines.hoc. This folder should have been created by the line
`t2n_initModelfolders(pwd);                                  % initialize model folder hierarchy in current folder`
in Tutorial A.
In order to be able to help you, I need more information, e.g. 
- what T2N version you are using (did you pull the latest version via git, or where did you get it from)
- if you followed the installation notes in the documentation word file, e.g. if you ran `t2n_runthisAfterUnzip.m`
- if you are running the live script simply by clicking on run or if you executed the tutorials in a different order (Tutorial A has to be run first always)

**Comment by LauraDovek** [comment]
Ok so to answer the questions, 
1. I did pull the latest version via git. for T2N
2. I ran the "T2N_run this afterUnZIP". then i moved to the tutorial
3. With the tutorial I just pressed RUN and it went through the whole thing. 

That being said, I noticed in another issue that you recommended to download the newer version of Neuron. I updated to Neuron 7.7 and now I have a lot less errors and warnings. I got rid of the one I previously asked about but now I get this error:
![image](https://user-images.githubusercontent.com/52047233/60744696-fedfca00-9f2b-11e9-94e7-6cd9f3612d37.png)

I am working on the warnings that I keep getting. Excited to be getting closer to having this work! 
Let me know if you have any suggestions.

**Comment by MarcelBeining** [comment]
Hi @LauraDovek ,
sorry to hear that there are still problems.
That other issue mainly affects Windows users as far as I understand, because there the builtin mpiexec is used which was errorneous in these versions.
As you seem to be a mac users (from the dialog you posted) you should make sure to have followed the installation instructions in the T2N handbook, which says:

> Note for Mac/Linux users: Matlab has to be run from the terminal for T2N to be properly working! For parallel NEURON to be working on Mac/Linux machines the OpenMPI software needs to be installed (https://www.open-mpi.org/software/ompi/ ). Here is the terminal command for installing under Linux:
> `sudo apt-get install openmpi-bin openmpi-common openssh-client openssh-server libopenmpi1.3 libopenmpi-dbg`
> Note for Linux users: If you experience problems during NEURON installation or the compilation of mod files, execute the following commands in the terminal in order to be sure that those packages necessary for compiling are installed:
> `sudo apt-get update `
>` sudo apt-get install g++ libxext-dev libncurses5-dev`

Did you follow these instructions, especially the installation of openmpi? Because your error message sounds like there is another mpiexec called on your system which does not allow specifying the number of cores to use with `-n`

**Comment by LauraDovek** [comment]
Hello Marcel, 
Thank you so much for being so helpful! 
I had downloaded openmpi using the instructions in Neuron. 
I have a mac so those instructions don't work on my system. Usually you can replace 'apt-get' to 'brew'

but I get this error "Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system."

Any ideas on where I can install this correctly on a mac? I know this isn't T2N related but I am excited to get this up and running!

**Comment by MarcelBeining** [comment]
Hi @LauraDovek ,
have you simply tried to use the brew command without sudo?
`brew install openmpi-bin openmpi-common openssh-client openssh-server libopenmpi1.3 libopenmpi-dbg`

**Comment by LauraDovek** [comment]
yes I have, and these are the errors I get
![image](https://user-images.githubusercontent.com/52047233/61497723-5d1d9b80-a975-11e9-8556-2994478208db.png)

**Comment by MarcelBeining** [comment]
Hi @LauraDovek ,
sorry for the late response.
Have you fixed this issue?
If not, please follow this guide:
http://macappstore.org/open-mpi/

if this does not work, follow this guide (without doing the fds stuff):
https://github.com/firemodels/fds/wiki/Installing-Open-MPI-on-OS-X

**Comment by LauraDovek** [comment]
Hi Marcel,
I did figure it out thank you so much for checking in.
I would share the solution but I had to change a lot of things on my
computer, if anyone has the same issues, look through the openmpi
frequently asked questions as they discuss how to change things
specifically for Macs to get it to work.
Kind regards,
Laura
